#!/bin/env bash
colors_path=$HOME/.cache/wal/colors.sh

mic=$(wpctl get-volume @DEFAULT_SOURCE@ | awk -F "Volume: " '{print $2}')
mic=$(echo "$mic * 100" | bc)
mic=$(printf "%.0f" "$mic")
if [ -f "$colors_path" ]; then
  source $colors_path
  echo "^c$color1^^b$color0^  $mic%^d^"
fi

