#!/bin/env bash
colors_path=$HOME/.cache/wal/colors.sh
if [ -f "$colors_path" ]; then
  source $colors_path
    echo "^c$color1^^b$color0^$(date +" %d, %I:%M%p") ^d^"
else 
  echo "$(date +" %H:%M%p ")"
fi
