#!/bin/sh
colors_path=$HOME/.cache/wal/colors.sh

vol=$(pamixer --get-volume --get-mute)

if [ -f "$colors_path" ]; then
  source $colors_path
  if [ -n "${vol%%false*}" ] ; then
      echo "^c$color0^^b$color8^ Muted ^d^"
  else
      echo "^c$color0^^b$color8^ Vol: ^d^^c$color0^^b$color4^ ${vol##* }% ^d^"
  fi
fi

