#!/bin/sh
colors_path=$HOME/.cache/wal/colors.sh

vol=$(pamixer --get-volume --get-mute)

if [ -f "$colors_path" ]; then
  source $colors_path
  if [ -n "${vol%%false*}" ] ; then
      echo "^b$color0^^c$color1^  ^d^"
  else
      echo "^c$color0^^b$color1^  ${vol##* }% ^d^"
  fi
fi

