#!/bin/sh
colors_path=$HOME/.cache/wal/colors.sh

if [ -f "$colors_path" ]; then
  source $colors_path
  if ! type "warp-cli" &> /dev/null; then return; fi
  if [[ "$(warp-cli status)" =~ .*"Connected".* ]]; then
    echo "^c$color1^^b$color0^ 󰒘 ^d^"
  else
    echo "^c$color8^^b$color0^ 󰫜 ^d^"
  fi
fi

